Update cura-installer-windows.yml

diff --git a/.github/workflows/cura-installer-windows.yml b/.github/workflows/cura-installer-windows.yml
--- a/.github/workflows/cura-installer-windows.yml
+++ b/.github/workflows/cura-installer-windows.yml
@@ -138,22 +138,27 @@ jobs:
         run: |
           Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Aswin21092002/cura-workflows/main/runner_scripts/prepare_installer.py" -OutFile "runner_scripts/prepare_installer.py"
 
-      # - name: Generate Installer File Name
-      #   id: prepare-installer
-      #   shell: powershell
-      #   run: |
-      #     $args = ""
-      #     if ("${{ inputs.enterprise }}" -eq "true") { $args += " --enterprise" }
-      #     if ("${{ inputs.conan_internal }}" -eq "true") { $args += " --internal" }
-      #     $installer_name = python runner_scripts/prepare_installer.py --os Windows --architecture X64 $args
-      #     echo "INSTALLER_NAME=$installer_name" | Out-File -FilePath $env:GITHUB_ENV -Append
-
+     
       
 
-      - name: Create Windows MSI Installer (Powershell)
+      - name: Ensure Clean Checkout
         run: |
-          python ..\cura_inst\packaging\msi\create_windows_msi.py ../cura_inst ./Fracktory "${{ env.INSTALLER_NAME }}.msi" "${{ inputs.app_name }}"
-        working-directory: dist
+          git reset --hard
+          git clean -fdx
+          git pull origin main
+      
+      - name: Verify File Exists
+        run: |
+          if (-Not (Test-Path "cura_inst/packaging/msi/create_windows_msi.py")) {
+            Write-Error "ERROR: create_windows_msi.py not found!"
+            exit 1
+          }
+        shell: powershell
+      
+      - name: Create Windows MSI Installer
+        run: |
+          python cura_inst/packaging/msi/create_windows_msi.py cura_inst ./Fracktory "${{ env.INSTALLER_NAME }}.msi" "${{ inputs.app_name }}"
+        working-directory: ${{ github.workspace }}
 
       - name: Create Windows EXE Installer (Powershell)
         run: |
